AppUTM.Client/Models/Empresa.cs
using Microsoft.AspNetCore.Http;

namespace AppUTM.Client.Models
{
    public class Empresa
    {
        public int EmpresaId { get; set; }
        public string RFC { get; set; }
        public string Nombre { get; set; }
        public string Alias { get; set; }
        public string Tipo { get; set; }
        public string Direccion { get; set; }
        public bool Activa { get; set; }
        public string Telefono { get; set; }
        public string ImagenEmpresa { get; set; }
        public IFormFile Foto { get; set; }    
        public bool Cupones { get; set; } = false;
    }
}

AppUTM.Client/Controllers/CuponesController.cs
using AppUTM.Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Identity.Web;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace AppUTM.Client.Controllers
{
    [Authorize]
    public class CuponesController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ITokenAcquisition _tokenAcquisition;

        HttpClient httpClient = new HttpClient();

        public CuponesController (IConfiguration configuration, ITokenAcquisition tokenAcquisition)
        {
            _configuration = configuration;
            _tokenAcquisition = tokenAcquisition;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int id)
        {
            Cupones cupones = new Cupones();
            var jsonEmpresa = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/" + id);
            var empresa = JsonConvert.DeserializeObject<Empresa>(jsonEmpresa);
            cupones.Empresa = empresa;
            var jsonCuponesGenerico = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/empresa/" + id);
            var listCupones = JsonConvert.DeserializeObject<IEnumerable<CuponGenerico>>(jsonCuponesGenerico).OrderByDescending(e => e.FechaExpiracion);
            cupones.cuponesGenericos = listCupones;
            var jsonCuponesImagen = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesImagen/empresa/" + id);
            var listCuponesImagen = JsonConvert.DeserializeObject<IEnumerable<CuponImagen>>(jsonCuponesImagen).OrderByDescending(e => e.FechaExpiracion);
            cupones.cuponesImagen = listCuponesImagen;          
            return View(cupones);
        }

        //  CUPONES GÉNERICOS
        [HttpGet]
        public async Task<ActionResult> Generico (int id)
        {
            var jsonCupon = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/" + id);
            var cupon = JsonConvert.DeserializeObject<CuponGenerico>(jsonCupon);
            return View(cupon);
        }

        public async Task<IActionResult> CreateGenerico(int id)
        {
            CuponGenerico cupon = new CuponGenerico();
            var jsonEmpresa = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/" + id);
            var empresa = JsonConvert.DeserializeObject<Empresa>(jsonEmpresa);
            cupon.EmpresaId = empresa.EmpresaId;
            cupon.NombreEmpresa = empresa.Nombre;
            return View(cupon);
        }

        [HttpPost]
        public async Task<IActionResult> CreateGenerico (CuponGenerico cupon)
        {
            var json = await httpClient.PostAsJsonAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/", cupon);
            if (json.IsSuccessStatusCode)
                return RedirectToAction ("Index", new { id = cupon.EmpresaId });
            else
                return RedirectToAction ("Error", "Home");
        }

        public async Task<IActionResult> UpdateGenerico (int id)
        {
            var json = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/ " + id);
            var cupon = JsonConvert.DeserializeObject<CuponGenerico>(json);           
            return View(cupon);
        }

        [HttpPost]
        public IActionResult UpdateGenerico(int id, CuponGenerico cupon)
        {
            httpClient.BaseAddress = new Uri(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/");
            var putTask = httpClient.PutAsJsonAsync<CuponGenerico>("?id=" + id, cupon);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
                return View (cupon);
            else
                return RedirectToAction ("Error", "Home");
        }

        public IActionResult DeleteGenerico (int empresaId, int id)
        {
            var deleteTask = httpClient.DeleteAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/" + id);
            deleteTask.Wait();
            if (deleteTask.Result.IsSuccessStatusCode)
                return RedirectToAction("Index", new { id = empresaId });
            else
                return RedirectToAction("Error", "Home");
        }



        //  ----------  CUPONES CON IMAGEN ----------//

        [HttpGet]
        public async Task<ActionResult> CuponImagen(int id)
        {
            var jsonCupon = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesImagen/" + id);
            var cupon = JsonConvert.DeserializeObject<CuponImagen>(jsonCupon);
            return View(cupon);
        }


        public async Task<IActionResult> CreateCuponImagen(int id)
        {
            CuponImagen cupon = new CuponImagen();
            var jsonEmpresa = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/" + id);
            var empresa = JsonConvert.DeserializeObject<Empresa>(jsonEmpresa);
            cupon.EmpresaId = empresa.EmpresaId;
            cupon.NombreEmpresa = empresa.Nombre;
            return View(cupon);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCuponImagen(CuponImagen cupon)
        {
            if(cupon.Foto != null)
            {
                using (var ms = new MemoryStream())
                {
                    await cupon.Foto.CopyToAsync(ms);
                    var fileBytes = ms.ToArray();
                    cupon.Imagen = Convert.ToBase64String(fileBytes);                
                }
            }      
            var json = await httpClient.PostAsJsonAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesImagen/", cupon);
            if (json.IsSuccessStatusCode)
                return RedirectToAction("Index", new { id = cupon.EmpresaId });
            else
                return RedirectToAction("Error", "Home");
        }      


        public async Task<IActionResult> UpdateCuponImagen(int id)
        {            
            var json = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesImagen/ " + id);
            var cupon = JsonConvert.DeserializeObject<CuponImagen>(json);
            return View(cupon);
        } 

        [HttpPost]
        public async Task<IActionResult> UpdateCuponImagen(int id, CuponImagen cupon)
        {
            if (cupon.Foto != null)
            {
                using (var sm = new MemoryStream())
                {
                    await cupon.Foto.CopyToAsync(sm);
                    var fileBytes = sm.ToArray();
                    cupon.Imagen = Convert.ToBase64String(fileBytes);
                }
            }
            httpClient.BaseAddress = new Uri(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesImagen/");
            var putTask = httpClient.PutAsJsonAsync<CuponImagen>("?id=" + id, cupon);
            putTask.Wait();
            if (putTask.Result.IsSuccessStatusCode)
                return View(cupon);
            else
                return RedirectToAction("Error", "Home");
        }

        public IActionResult DeleteCuponImagen(int empresaId, int id)
        {
            var deleteTask = httpClient.DeleteAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesImagen/" + id);
            deleteTask.Wait();
            if (deleteTask.Result.IsSuccessStatusCode)
                return RedirectToAction("Index", new { id = empresaId });
            else
                return RedirectToAction("Error", "Home");
        }


        /* Guardar imagen 
        private string UploadImage(CuponImagen cupon)
        {
            string fileName = null, filePath = null;
            if (cupon.Foto != null)
            {
                string path = cupon.Domain + @"\wwwroot\Cupones\";
                fileName = Guid.NewGuid().ToString() + "-" + cupon.Foto.FileName;
                filePath = Path.Combine(path, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    cupon.Foto.CopyTo(fileStream);
                }
            }
            return fileName;
        }

        */
    }
}

AppUTM.Client/Controllers/EmpresasController.cs
using AppUTM.Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Web;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace AppUTM.Client.Controllers
{
    [Authorize]
    public class EmpresasController : Controller
    {
        private readonly ILogger<EmpresasController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly IConfiguration _configuration;
        private readonly ITokenAcquisition _tokenAcquisition;
        private readonly HttpClient _httpClient;
        private readonly string _scope;

        public EmpresasController(ILogger<EmpresasController> logger, IConfiguration configuration, ITokenAcquisition tokenAcquisition, HttpClient httpClient, IWebHostEnvironment environment)
        {
            _logger = logger;
            _configuration = configuration;
            _tokenAcquisition = tokenAcquisition;
            _httpClient = httpClient;
            _environment = environment;
            _scope = "user.read";
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            HttpClient httpClient = new HttpClient();
            ListEmpresas listEmpresas = new ListEmpresas();
            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);
            var jsonEmpresas = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/all");
            listEmpresas.empresasRegistradas = JsonConvert.DeserializeObject<List<Empresa>>(jsonEmpresas).OrderByDescending(e => e.EmpresaId);
            //Muestra las empresas que proporciona la API de la UTM
            var jsonEmpresasUTM = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/empresasUTM");
            listEmpresas.empresasUTM = System.Text.Json.JsonSerializer.Deserialize<List<EmpresasUTM>>(jsonEmpresasUTM);
            List<EmpresasUTM> empresasUTM = new List<EmpresasUTM>();
            foreach (var item in listEmpresas.empresasUTM)
            {
                if (!listEmpresas.empresasRegistradas.Any(e => e.RFC == item.RFC))
                    empresasUTM.Add(item);
            }
            listEmpresas.empresasUTM = empresasUTM;
            return View(listEmpresas);
        }

        public IActionResult Create(string RFC, string Nombre, string Direccion, string Telefono)
        {   
            Empresa empresa = new Empresa();          
            empresa.RFC = RFC;
            empresa.Nombre = Nombre;
            empresa.Direccion = Direccion;
            empresa.Telefono = Telefono;    
            return View(empresa);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Empresa empresa)
        {
            HttpClient httpClient = new HttpClient();           
            if (empresa.Foto != null)
            {
                using (var sm = new MemoryStream())
                {
                    await empresa.Foto.CopyToAsync(sm);
                    var fileBytes = sm.ToArray();
                    empresa.ImagenEmpresa = Convert.ToBase64String(fileBytes);
                }
            }
            else
            {
                using (var sm = new MemoryStream())
                {
                    var path = _environment.WebRootPath + "/img/xcompany.jpg";
                    Byte[] bytes = System.IO.File.ReadAllBytes(path);
                    empresa.ImagenEmpresa = Convert.ToBase64String(bytes);                
                }
            }
            var json = await httpClient.PostAsJsonAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas", empresa);
            if (json.IsSuccessStatusCode)
                return RedirectToAction("Index");
            else
                return RedirectToAction("Error", "Home");
        }
       
        public async Task<IActionResult> Update(int id)
        {
            HttpClient httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/" + id);
            var empresa = JsonConvert.DeserializeObject<Empresa>(json);
            var jsonCuponesGenericos = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/empresa/" + id);
            var jsonCuponesImagen = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "CuponesGenericos/empresa/" + id);
            if (jsonCuponesGenericos.Length > 5 || jsonCuponesImagen.Length > 5) empresa.Cupones = true;
            return View(empresa);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Empresa empresa)
        {
            HttpClient httpClient = new HttpClient();

            if (empresa.Foto != null)
            {
                using (var sm = new MemoryStream())
                {
                    await empresa.Foto.CopyToAsync(sm);
                    var fileBytes = sm.ToArray();
                    empresa.ImagenEmpresa = Convert.ToBase64String(fileBytes);
                }
            }
            httpClient.BaseAddress = new Uri(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/");
            var putTask = httpClient.PutAsJsonAsync<Empresa>("?id=" + id, empresa);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
                return View(empresa);
            else
                return RedirectToAction("Error", "Home");
        }

        [HttpPut]
        public async Task<IActionResult> Desactivar(int id)
        {
            HttpClient httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/Desactivar/" + id);
            var empresa = JsonConvert.DeserializeObject<Empresa>(json);
            return View(empresa);
        }

        public IActionResult DeleteEmpresas(int empresaId, int id)
        {
            HttpClient httpClient = new HttpClient();

            var deleteTask = httpClient.DeleteAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/" + id);
            deleteTask.Wait();
            if (deleteTask.Result.IsSuccessStatusCode)
                return RedirectToAction("Index", new { id = empresaId });
            else
                return RedirectToAction("Error", "Home");
        }

        private async Task PrepareAuthenticatedClient()
        {
            var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { _scope });
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }


        private async Task<string> GetPhoto(HttpClient client)
        {
            var resp = await client.GetAsync(_configuration["photouser"]);
            var buffer = await resp.Content.ReadAsByteArrayAsync();
            var byteArray = buffer.ToArray();

            string base64String = Convert.ToBase64String(byteArray);

            return base64String;
        }
    }
}

AppUTM.Client/Views/Empresas/Create.cshtml
@model AppUTM.Client.Models.Empresa
@{
    ViewData["Title"] = "Agregar una nueva de empresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Datos de @Model.Nombre</h4>
<form asp-action="Create" enctype="multipart/form-data">
    <div class="form-group row mt-4">   
        <div class="form-group col-md-4">
            <label>RFC</label>
            @if (Model.RFC != null)
            {
                <label class="form-control disabled-input">@Model.RFC</label>
            }
            else
            {
                <label class="form-control disabled-input">No disponible</label>
            }
            <input type="hidden" class="form-control" asp-for="RFC" value="@Model.RFC" />
        </div>
        <div class="form-group col-md-6">
            <label>Nombre</label>
            <label class="form-control disabled-input">@Model.Nombre</label>
            <input type="hidden" class="form-control" asp-for="Nombre" value="@Model.Nombre" />
        </div>
        <div class="form-group col-md-2">
            <label>Teléfono</label>
            @if (Model.Telefono != null)
            {
                <label class="form-control disabled-input">@Model.Telefono</label>
            }
            else
            {
                <label class="form-control disabled-input">No disponible</label>
            }
            <input type="hidden" class="form-control" asp-for="Telefono" value="@Model.Telefono">
        </div>       
    </div>
    <div class="form-group row mt-4">

        <div class="form-group col-md-4">
            <label>Estado</label>
            <label class="form-control disabled-input">True</label>
            <input type="hidden" class="form-control" asp-for="Activa" value="True" />
        </div>
        <div class="form-group col-md-8">
            <label>Dirección</label>
            <label class="form-control disabled-input">@Model.Direccion</label>
            <input type="hidden" class="form-control" name="Direccion" asp-for="@Model.Direccion">
        </div>
    </div>   
    <div class="form-group row mt-4">
        <div class="form-group col-md-3">
            <label>Alias</label>
            <input type="text" class="form-control" asp-for="Alias" required />
        </div>
        <div class="form-group col-md-4">
            <label>Tipo</label>
            <input type="text" class="form-control" asp-for="Tipo" required />
        </div>
    </div>
    <div class="d-flex">
        <div class="mt-5">
            <label for="">Agregar Imagen</label>
            <input class="form-control" type="file" name="Foto">
        </div>

    </div>
    <div>
        <input type="submit" class="btn btn-green mt-4" value="Agregar Empresa" />
        <a class="btn btn-secondary mt-4" asp-action="Index">Cancelar/Regresar</a>
    </div>
</form>

AppUTM.Client/Views/Empresas/Index.cshtml
@model AppUTM.Client.Models.ListEmpresas;
@{
    ViewData["Title"] = "Empresas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/filter.js"></script>
<h4>Empresas con descuento</h4>
<div class="container mt-3">
    <div class="mb-4 d-flex">
        <input class="form-control me-3" type="search" id="inputTable" onkeyup="searchInTable()" aria-label="Search" placeholder="Buscar empresa...">
        <button class="btn btn-outline-dark btn-add" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">Agregar</button>
        <!-- Modal agregar empresa  -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle">Seleccione una empresa para registrar cupón</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">                  
                        <input class="form-control me-3 mb-3" type="search" id="inputModalTable" onkeyup="searchInModalTable()" aria-label="Search" placeholder="Buscar empresa...">
                        <table class="table table-bordered modal-table">
                            <tbody id="myModalTable">
                                @foreach (var item in Model.empresasUTM)
                                {
                                <tr>
                                    <td>@item.NombreEmpresa</td>
                                    @if (item.RFC != null)
                                    {
                                        <td>
                                            <a class="button-a" asp-controller="Empresas" asp-action="Create" asp-route-RFC="@item.RFC"
                                               asp-route-Nombre="@item.NombreEmpresa" asp-route-Direccion="@item.Direccion" asp-route-Telefono="@item.Telefono">Registrar</a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="text-danger">
                                            No dispone de RFC
                                        </td>
                                    }
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <table class="table table-bordered main-table">
        <tbody id="myTable">
            @foreach (var item in Model.empresasRegistradas)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td><a asp-controller="Cupones" asp-action="Index" asp-route-Id="@item.EmpresaId">Cupones</a></td>
                    <td><a asp-action="Update" asp-route-Id="@item.EmpresaId">Detalles</a></td>
                </tr>
            }
        </tbody>
    </table>   
</div>

<!-- Método auxiliar del filtro-->
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

AppUTM.Client/Views/Empresas/Update.cshtml
@model AppUTM.Client.Models.Empresa
@{
    ViewData["Title"] = "Actualizar datos de empresa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Datos de @Model.Nombre</h4>
<form asp-action="Update" enctype="multipart/form-data">
    <div class="form-group row mt-4">
        <input type="hidden" asp-for="EmpresaId" value="@Model.EmpresaId">   
        <div class="form-group col-md-4">
            <label>RFC</label>
            @if (Model.RFC != null)
            {
                <label class="form-control disabled-input">@Model.RFC</label>
            }
            else
            {
                <label class="form-control disabled-input">No disponible</label>
            }
            <input style="background-color:gray" type="hidden" class="form-control" asp-for="RFC" value="@Model.RFC">
        </div>
        <div class="form-group col-md-6">
            <label>Nombre</label>
            <label class="form-control disabled-input">@Model.Nombre</label>
            <input type="hidden" class="form-control" asp-for="Nombre" value="@Model.Nombre">
        </div>
        <div class="form-group col-md-2">
            <label>Teléfono</label>
            @if (Model.Telefono != null)
            {
                <label class="form-control disabled-input">@Model.Telefono</label>
            }
            else
            {
                <label class="form-control disabled-input">No disponible</label>
            }
            <input type="hidden" class="form-control" asp-for="Telefono" value="@Model.Telefono">
        </div>
    </div>
    <div class="form-group row mt-4">
        <div class="form-group col-md-4">
            <label>Estado</label>
            <label class="form-control disabled-input">@Model.Activa</label>
            <input type="hidden" class="form-control" asp-for="Activa" value="@Model.Activa">
        </div>
        <div class="form-group col-md-8">
            <label>Dirección</label>         
            <label class="form-control disabled-input">@Model.Direccion</label>
            <input type="hidden" class="form-control" name="Direccion" asp-for="@Model.Direccion">
        </div>       
    </div>
    <div class="form-group row mt-4">
        <div class="form-group col-md-4">
            <label>Alias</label>
            <input type="text" class="form-control" asp-for="Alias" value="@Model.Alias">
        </div>
        <div class="form-group col-md-4">
            <label>Tipo</label>
            <input type="text" class="form-control" asp-for="Tipo" value="@Model.Tipo">
        </div>
    </div>
    <div class="d-flex">
        <div class="mt-5">
            <label for="">Cambiar imagen</label>
            <input class="form-control" type="file" name="Foto">
            <input type="hidden" name="ImagenEmpresa" asp-for="@Model.ImagenEmpresa" />
        </div>
        <img class="mx-2 mt-3" id="company" src="data:image/jpeg;base64, @Model.ImagenEmpresa" alt="@Model.ImagenEmpresa">
    </div>
    <div>
        <input type="submit" class="btn btn-green mt-4" value="Guardar Datos" />
        @if (Model.Cupones)
        {
            <button type="button" class="btn btn-danger mt-4 mx-3" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">Desactivar Empresa</button>
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <p id="exampleModalCenterTitle" class="w-100 text-center">¿Desea desactivar esta empresa?</p>
                        </div>
                        <div class="modal-body mx-auto">
                            <a asp-route-EmpresaId="@Model.EmpresaId" asp-route-Id="@Model.EmpresaId" asp-action="Desactivar" class="btn btn-danger">Desactivar Empresa</a>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>

        }
        else
        {
            <button type="button" class="btn btn-danger mt-4 mx-3" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">Eliminar Empresa</button>
            <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <p id="exampleModalCenterTitle" class="w-100 text-center">Esta empresa no tiene cupones ligados, ¿Desea eliminarla?</p>
                        </div>
                        <div class="modal-body mx-auto">
                            <a asp-route-EmpresaId="@Model.EmpresaId" asp-route-Id="@Model.EmpresaId" asp-action="DeleteEmpresas" class="btn btn-danger">Eliminar Empresa</a>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        </div>
                    </div>
                </div>
            </div>
        }
        <a class="btn btn-secondary mt-4" asp-action="Index">Cancelar/Regresar</a>
    </div>
</form>