AppUTM.Client/Controllers/ReporteController.cs
using AppUTM.Client.Models;
using AppUTM.Client.Responses;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Web;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace AppUTM.Client.Controllers
{
   
    [Authorize]
    public class ReporteController : Controller
    {
        private readonly ILogger<ReporteController> _logger;
        private readonly ITokenAcquisition _tokenAcquisition;
        private readonly string _scope;
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;

        public ReporteController(ILogger<ReporteController> logger, ITokenAcquisition tokenAcquisition, HttpClient httpClient, IConfiguration configuration)
        {
            _logger = logger;
            _tokenAcquisition = tokenAcquisition;
            _httpClient = httpClient;
            _configuration = configuration;
            _scope = "user.read";
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);

            HttpClient httpClient = new HttpClient();
            //http://api.utmetropolitana.edu.mx/api/Empresas/Get
            //http://localhost:59131/api/Empresas
            ListEmpresas listEmpresas = new ListEmpresas();
            var jsonEmpresas = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas");
            listEmpresas.empresasRegistradas = JsonConvert.DeserializeObject<List<Empresa>>(jsonEmpresas);
            var jsonEmpresasUTM = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/empresasUTM");
            listEmpresas.empresasUTM = System.Text.Json.JsonSerializer.Deserialize<IEnumerable<EmpresasUTM>>(jsonEmpresasUTM);



            return View(listEmpresas);
        }
        [HttpGet]
        public async Task<IActionResult> EmpresasDesactivadas()
        {
            HttpClient httpClient = new HttpClient();
            ListEmpresas listEmpresas = new ListEmpresas();
            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);
            var jsonEmpresas = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/all");
            listEmpresas.empresasRegistradas = JsonConvert.DeserializeObject<List<Empresa>>(jsonEmpresas).OrderByDescending(e => e.EmpresaId);
            //Muestra las empresas que proporciona la API de la UTM
            var jsonEmpresasUTM = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/empresasUTM");
            listEmpresas.empresasUTM = System.Text.Json.JsonSerializer.Deserialize<List<EmpresasUTM>>(jsonEmpresasUTM).Where(e => e.RFC != null);
            List<EmpresasUTM> empresasUTM = new List<EmpresasUTM>();
            foreach (var item in listEmpresas.empresasUTM)
            {
                if (!listEmpresas.empresasRegistradas.Any(e => e.RFC == item.RFC))
                    empresasUTM.Add(item);
            }
            listEmpresas.empresasUTM = empresasUTM;
            return View(listEmpresas);
        }

        public async Task<IActionResult> Update(int id)
        {
            HttpClient httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/" + id);
            var empresa = JsonConvert.DeserializeObject<Empresa>(json);
            return View(empresa);
        }

        [HttpPost]
        public IActionResult Update(int id, Empresa empresa)
        {
            HttpClient httpClient = new HttpClient();         
            httpClient.BaseAddress = new Uri(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Empresas/");
            var putTask = httpClient.PutAsJsonAsync<Empresa>("?id=" + id, empresa);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
                return View(empresa);
            else
                return RedirectToAction("Error", "Home");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private async Task PrepareAuthenticatedClient()
        {
            var accessToken = await _tokenAcquisition.GetAccessTokenForUserAsync(new[] { _scope });
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        private async Task<string> GetPhoto(HttpClient client)
        {
            var resp = await client.GetAsync(_configuration["photouser"]);
            var buffer = await resp.Content.ReadAsByteArrayAsync();
            var byteArray = buffer.ToArray();

            string base64String = Convert.ToBase64String(byteArray);

            return base64String;
        }

        public IActionResult Empresa()
        {
            return View();
        }
    }
}

AppUTM.Client/Controllers/UsuarioController.cs
using AppUTM.Api.DTOS.Users;
using AppUTM.Client.Models;
using AppUTM.Client.Models.Roles;
using AppUTM.Client.Models.Users;
using AppUTM.Client.Responses;
using AppUTM.Core.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Web;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace AppUTM.Client.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly ILogger<UsuarioController> _logger;
        private readonly ITokenAcquisition _tokenAcquisition;
        private readonly string _scope;
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;

        public UsuarioController(ILogger<UsuarioController> logger, ITokenAcquisition tokenAcquisition, HttpClient httpClient, IConfiguration configuration)
        {
            _logger = logger;
            _tokenAcquisition = tokenAcquisition;
            _httpClient = httpClient;
            _configuration = configuration;
            _scope = "user.read";
        }


        //_Configuration["CouponAdmin:CouponAdminBaseAddress"] + ""
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            HttpClient httpClient = new HttpClient();

            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);


            var jsonUser = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users");
            var jsonRoles = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Roles");

            //var jsonUser = await httpClient.GetStringAsync("http://localhost:59131/api/Users");
            // var jsonRoles = await httpClient.GetStringAsync("http://localhost:59131/api/Roles/");
            var listRoles = JsonConvert.DeserializeObject<ApiResponse<List<RoleReturn>>>(jsonRoles);
            ViewBag.Roles = listRoles.Data;
            var listUsuario = JsonConvert.DeserializeObject<ApiResponse<List<UserReturn>>>(jsonUser);
            return View(listUsuario.Data);
        }

        [HttpGet] //Vista para busqueda
        public async Task<IActionResult> EmpleadosAsync()
        {
            HttpClient httpClient = new HttpClient();
            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);
            return View();
        }

        // GET: Empleado
        [HttpGet]
        public async Task<IActionResult> EmpleadoConsulta(string correo)
        {
            HttpClient httpClient = new HttpClient();

            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);

            List<EmpleadoUTM> listemp = new List<EmpleadoUTM>();
            //Busqueda BD LOCAL
            var jsonemp = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users");
            var listUsuario = JsonConvert.DeserializeObject<ApiResponse<List<UserReturn>>>(jsonemp);
            ViewBag.listuser = listUsuario.Data;

            //Muestra los empleados que proporciona la API de la UTM
            var jsonEmpleado = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users/" + "empleado/" + correo);
            // var jsonEmpleado = await httpClient.GetStringAsync("http://localhost:59131/api/Users/empleado/" + correo);
            var jsonlist = JsonConvert.DeserializeObject<List<EmpleadoUTM>>(jsonEmpleado);
            if (jsonlist.Count == 0)
            {
                ViewBag.error = "El correo que introdujo no existe";
                return View(jsonlist);
            }
            else
            {
                ViewBag.listemp = jsonlist;
                return View(jsonlist);
            }
        }
        // GET: UsuarioController

        // GET: UsuarioController/Details/5
        public async Task<ActionResult> Detalles(int id)
        {
            HttpClient httpClient = new HttpClient();

            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);
            var jsonUser = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users/" + id);
            //var jsonUser = await httpClient.GetStringAsync("http://localhost:59131/api/Users/" + id);
            var listUsuario = JsonConvert.DeserializeObject<ApiResponse<UserReturn>>(jsonUser);
            return View(listUsuario.Data);
        }
        [HttpGet]
        public async Task<ActionResult> Create(int ClaveEmpleado, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string Correo)
        {
            HttpClient httpClient = new HttpClient();

            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);
            User empleado = new User();
            empleado.ClaveEmpleado = ClaveEmpleado;
            empleado.Nombres = Nombres;
            empleado.ApellidoPaterno = ApellidoPaterno;
            empleado.ApellidoMaterno = ApellidoMaterno;
            empleado.Correo = Correo;
            var json2 = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users");
            var jsonUser = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Roles");
            //var json = await httpClient.GetStringAsync("http://localhost:59131/api/Users/");
            //var jsonUser = await httpClient.GetStringAsync("http://localhost:59131/api/Roles/");
            var listRoles = JsonConvert.DeserializeObject<ApiResponse<List<RoleReturn>>>(jsonUser);
            
            ViewBag.Roles = listRoles.Data;
            var crear = JsonConvert.DeserializeObject<UserCreate>(json2);
            return View(crear);
        }

        [HttpPost]
        public async Task <IActionResult> Create(UserCreate userCreate, int[] role)
        {
            HttpClient httpClient = new HttpClient();

            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);

            List<UserRole> listaRoles = new List<UserRole>();
            foreach (var item in role)
            {
                UserRole roleUser = new UserRole();
                roleUser.RoleId = item;
                listaRoles.Add(roleUser);
            }
            userCreate.UserRoles = listaRoles;

            var CrearCliente = httpClient.PostAsJsonAsync<UserCreate>(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users", userCreate);
            CrearCliente.Wait();

            var CreaResult = CrearCliente.Result;
            if (CreaResult.IsSuccessStatusCode)
                return RedirectToAction("Index");
            else
                return this.BadRequest();
        }


        // GET: UsuarioController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            HttpClient httpClient = new HttpClient();

            await PrepareAuthenticatedClient();
            string json = await _httpClient.GetStringAsync(_configuration["getuseraddress"]);
            ViewBag.image = await GetPhoto(_httpClient);


            var json2 = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users/" + id);
            var jsonUser = await httpClient.GetStringAsync(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Roles");
            var listRoles = JsonConvert.DeserializeObject<ApiResponse<List<RoleReturn>>>(jsonUser);
            var crear = JsonConvert.DeserializeObject<ApiResponse<UserForUpdateDto>>(json2);

            foreach (var rol in crear.Data.UserRoles)
            {
                listRoles.Data.Remove(listRoles.Data.Single(r => rol.RoleId == r.Id));

            }

            ViewBag.Roles = listRoles.Data;

            return View(crear.Data);

        }

        // POST: UsuarioController/Edit/5
        [HttpPost]

        public async Task<ActionResult> Edit(int id, UserForUpdateDto userForUpdateDto, int[] roleDelete, int[] roleAdd)
        {
            HttpClient httpClient = new HttpClient();
            //List<UserRole> listaRoles = new List<UserRole>();
            if (roleDelete != null)
            {
                userForUpdateDto.RolesToBeDelete = roleDelete;
            }

            if (roleAdd != null)
            {
                userForUpdateDto.UserRoles = new List<UserRole>();

                foreach (var item in roleAdd)
                {
                    UserRole roleUser = new UserRole();
                    roleUser.RoleId = item;
                    userForUpdateDto.UserRoles.Add(roleUser);

                }

            }
            var updateClient = await httpClient.PutAsJsonAsync<UserForUpdateDto>(_configuration["CouponAdmin:CouponAdminBaseAddress"] + "Users/" + userForUpdateDto.Id, userForUpdateDto);
            if (updateClient.IsSuccessStatusCode)
                return RedirectToAction("Index");
            else
                return this.BadRequest();
        }

        // GET: UsuarioController/Delete/5

AppUTM.Client/Views/Shared/_Layout.cshtml
@using Microsoft.Identity.Web
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - AppUTM</title>
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/main.css">
    <link rel="stylesheet" href="css/avatar.css" />
    <style>
        .dropdown-menu {
            background-color: #90cb59;
        }

        a.dropdown-item {
            background-color: transparent;
            color: white;
        }

            a.dropdown-item:hover {
                /*Modifica lo que quieras*/
                background: transparent;
                /*            color: white;*/
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img src="~/img/logo.png" id="logo" alt="UTM">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="me-auto"></div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="me-auto"></div>
                    <ul class="navbar-nav mb-2 mb-lg-2 fw-bold d-flex">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Empresas" asp-action="Index">Empresas</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Reporte" asp-action="Index">Reporte</a>
                        </li>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Reportes
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" aria-current="page" asp-controller="Reporte" asp-action="Index">Empresas con cupones</a></li>
                                <li><a class="dropdown-item" aria-current="page" asp-controller="Reporte" asp-action="EmpresasDesactivadas">Empresas sin cupones</a></li>
                                <li><a class="dropdown-item" aria-current="page" asp-controller="HistorialCupones" asp-action="Index">Usos por divisiones</a></li>
                            </ul>

                        </li>
                        @*<li class="nav-item">
                                    <div class="container-fluid">
                                    <a class="navbar-brand" href="#">Seguridad</a>
                            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                                    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                                        <ul class="navbar-nav">*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" style="color:black" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Seguridad
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Usuario" asp-action="Index">Usuarios</a></li>
                                <li><a class="dropdown-item" asp-controller="Module" asp-action="Index">Modulos</a></li>
                                <li><a class="dropdown-item" asp-controller="ModuleRole" asp-action="Index">Acceso a modulos</a></li>
                                <li><a class="dropdown-item" asp-controller="Roles" asp-action="Index">Roles</a></li>
                            </ul>
                        </li>
                    </ul>

                </div>

            </div>
        </div>
        <div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="me-auto"></div>
                <ul class="navbar-nav mb-2 mb-lg-2 fw-bold d-flex">
                    <li class="nav-link dropdown active">
                        <p class="nav-item"></p>
                        <a class="nav-item pe-0" id="navbarDropdownUser" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div class="avatar avatar-48">
                                <img style="width: 52px; height: auto;" class="rounded-circle" src="data:image/png;base64,@ViewBag.image" alt="">
                            </div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end py-0" aria-labelledby="navbarDropdownUser">
                            <div class="bg-white dark__bg-1000 rounded-2 py-2">
                                <a asp-area="MicrosoftIdentity" class="nav-link active" asp-controller="Account" asp-action="SignOut" aria-current="page">Cerrar Sesión</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3 mt-2">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
</script>